<form action="">
    <input type="hidden" name="id" value="<?php echo $this->getId() ?>" required>
    <input type="number" placeholder="limit" name="limit" required>
    <input type="submit" class="w-25">
</form>
<div class="d-flex">
    <a href="<?php echo '?id=' . $this->getId() ?>&showcompleted=true"><button id="showcompleted"
            class='bg-warning'>show
            completed</button></a>
    <a href="<?php echo '?id=' . $this->getId() ?>"><button id="showall" class='bg-secondary'>hide
            completed</button></a>
    <button id="saveall" class='bg-primary'>saveAll</button>
</div>
<span class="d-none" id="maxlevel"><?php echo $this->getMaximumLevel() ?></span>
<?php
echo $this->render();
?>
<span id="ticketId" class="d-none"><?php echo $this->getId() ?></span>