<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow-lg border-0 rounded-3">
                <div class="card-body p-5">
                    <h1 class="text-center text-primary mb-5 fw-bold">Hello, Admin <i
                            class="bi bi-emoji-smile text-warning"></i></h1>

                    <div class="row justify-content-center gap-4 mt-4">
                        <div class="col-md-5">
                            <div class="d-grid">
                                <a href="<?php echo $this->getUrl('*/category_index/list'); ?>"
                                    class="text-decoration-none">
                                    <button class="btn btn-primary btn-lg py-3 fw-semibold shadow-sm w-100">
                                        <i class="bi bi-folder me-2"></i> Category List
                                    </button>
                                </a>
                            </div>
                        </div>

                        <div class="col-md-5">
                            <div class="d-grid">
                                <a href="<?php echo $this->getUrl('*/product_index/list'); ?>"
                                    class="text-decoration-none">
                                    <button class="btn btn-success btn-lg py-3 fw-semibold shadow-sm w-100">
                                        <i class="bi bi-box me-2"></i> Product List
                                    </button>
                                </a>
                            </div>
                        </div>

                        <div class="col-md-5">
                            <div class="d-grid">
                                <a href="<?php echo $this->getUrl('*/order/index'); ?>" class="text-decoration-none">
                                    <button class="btn btn-info btn-lg py-3 fw-semibold shadow-sm w-100 text-white">
                                        <i class="bi bi-cart me-2"></i> All Orders
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>