<?php
$columns = $this->getColumns();
?>

<br>

<div class="container mw-100">

    <div class="row">
        <div class="col-12">
            <div class="card shadow rounded-3 mb-5">
                <div class="card-header bg-primary text-white">
                    <h2 class="m-0 text-white">Admin Grid</h2>
                </div>
                <?php $this->getChildHtml('toolbar'); ?>
                <?php $this->getChildHtml('export'); ?>
                <div class="card-body">
                    <a href="./new" class="btn btn-success mb-4">
                        <i class="fas fa-plus-circle me-2"></i>Insert New
                    </a>
                    <?php $this->getChildHtml('csv') ?>

                    <div class="table-responsive">
                        <table class="table table-striped table-hover align-middle mb-0" id="producttable1">
                            <thead class="table-dark">
                                <tr>
                                    <?php foreach ($columns as $column): ?>
                                    <th><?php echo $column->getData()['lable'] ?></th>
                                    <?php endforeach; ?>
                                </tr>
                                <!-- <button id="clearFilter">clearFilter</button> -->
                                <tr id="filter">
                                    <?php foreach ($columns as $column):
                                    ?>
                                    <th><?php
                                            echo $column->getFilter()->render();
                                            ?></th>
                                    <?php endforeach;
                                    ?>
                                </tr>
                            </thead>
                            <tbody id="grid_data">
                                <?php foreach ($this->getCollection()->getData() as $row): ?>
                                <tr>
                                    <?php foreach ($columns as $column): ?>
                                    <td><?php
                                                $column->setRow($row);
                                                echo $column->render();
                                                ?></td>
                                    <?php endforeach; ?>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
// console.log("123");
$(function() {
    $(document).on('input', 'input', function(event) {
        let dataobj = {};
        let filterdata = $('#filter').find('input').each(function() {
            dataobj[$(this).attr("name")] = $(this).val();
        });
        let queryString = $.param(dataobj);
        let fullUrl = '?' + queryString;
        window.history.pushState({}, '', fullUrl);
        $.ajax({
            url: `http://localhost${window.location.pathname}`,
            type: 'get',
            data: dataobj,
            success: function(res) {
                $("#grid_data").empty().html($(res).find("#grid_data").html());
                $(".pagination ").empty().html($(res).find(".pagination ").html());
            },
            error: function(err) {
                console.log(err);
            },
        });
    });
});
$('select').on('change', function() {
    $('form').submit();
});
</script>