    <?php
    $events = $this->getEvents();
    // Mage::log($events);
    // die;
    ?>

    <br>

    <div class="container mw-100">
        <div class="row">
            <div class="col-12">
                <div class="card shadow rounded-3 mb-5">
                    <div class="card-header bg-primary text-white">
                        <h2 class="m-0 text-white">event list</h2>
                    </div>
                    <div class="card-body">
                        <a href="./add" class="btn btn-success mb-4">
                            <i class="fas fa-plus-circle me-2"></i>add event
                        </a>

                        <?php $this->getChildHtml('toolbar')
                        ?>

                        <div class="table-responsive">
                            <table class="table table-striped table-hover align-middle mb-0" id="producttable1">
                                <thead class="table-dark">
                                    <tr>
                                        <th>Event Id</th>
                                        <th>title</th>
                                        <th>Description</th>
                                        <th>Date</th>
                                        <th>Location</th>
                                        <th>capacity</th>
                                        <th>Created By</th>
                                        <th>Created date</th>
                                        <th>total registrations </th>
                                        <th>Edit</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($events as $event): ?>
                                    <tr>
                                        <td><?php echo $event->getEventId() ?></td>
                                        <td><?php echo $event->getTitle() ?></td>
                                        <td><?php echo $event->getDescription() ?></td>
                                        <td><?php echo $event->getDate() ?></td>
                                        <td><?php echo $event->getLocation() ?></td>
                                        <td><?php echo $event->getCapacity() ?></td>
                                        <td><?php echo $event->getCreatedBy() ?></td>
                                        <td><?php echo $event->getCreatedDate() ?></td>
                                        <?php //Mage::log($event); 
                                            ?>
                                        <td><a
                                                href="./eventUsers?id=<?php echo $event->getEventId() ?>"><?php echo $event->EventCount() ?></a>
                                        </td>
                                        <td><a href="./add?id=<?php echo $event->getEventId() ?>">Edit</a></td>
                                        <td><a href="./delete?id=<?php echo $event->getEventId() ?>">Delete</a></td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>