<?php
$events = $this->getEvents();
// $isRegistred = $this->getIsRegistred();
$pastevents = $this->getPastEvents();
// Mage::log($pastevents);
?>

<br>

<div class="container mw-100">
    <div class="row">
        <div class="col-12">
            <div class="card shadow rounded-3 mb-5">
                <div class="card-header bg-primary text-white">
                    <h2 class="m-0 text-white">upcomming events</h2>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover align-middle mb-0" id="producttable1">
                            <thead class="table-dark">
                                <tr>
                                    <th>title</th>
                                    <th>Description</th>
                                    <th>Date</th>
                                    <th>Location</th>
                                    <th>action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($events as $event): ?>
                                <tr>
                                    <td><?php echo $event->getTitle() ?></td>
                                    <td><?php echo $event->getDescription() ?></td>
                                    <td><?php echo $event->getDate() ?></td>
                                    <td><?php echo $event->getLocation() ?></td>
                                    <td>
                                        <?php if (!$event->isRegistred() && !$event->isExeed()): ?>
                                        <a href="./register?id=<?php echo $event->getEventId() ?>"
                                            onclick="return confirm('sure to register for event')">
                                            <button>register</button>
                                        </a>
                                        <?php elseif ($event->isRegistred()): ?>
                                        <span><?php echo $event->status() ?></span>
                                        <?php endif; ?>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="card shadow rounded-3 mb-5">
                <div class="card-header bg-primary text-white">
                    <h2 class="m-0 text-white">past events</h2>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover align-middle mb-0" id="producttable1">
                            <thead class="table-dark">
                                <tr>
                                    <th>title</th>
                                    <th>Description</th>
                                    <th>Date</th>
                                    <th>Location</th>
                                    <th>status</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($pastevents as $event): ?>
                                <tr>
                                    <td><?php echo $event->getTitle() ?></td>
                                    <td><?php echo $event->getDescription() ?></td>
                                    <td><?php echo $event->getDate() ?></td>
                                    <td><?php echo $event->getLocation() ?></td>
                                    <td><?php echo $event->getStatus() ?></td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>