<?php
$id = Mage::getSingleton('core/request')->getQuery('id');
?>
<div class="container py-5">
    <h4 class="mb-2 mb-md-0 fw-bold text-primary">
        <?php echo ($id) ? $this->getCategoryName($id) : "All" ?> Category Products
    </h4>
    <div
        class="d-flex flex-column flex-md-row justify-content-between align-items-center bg-light rounded-3 p-4 shadow-sm mb-4">
        <div class="d-flex flex-column align-items-center">
            <input type="text" id="search-input" class="form-control w-100 w-md-75" placeholder="Search product name">
        </div>
        <div class="d-flex gap-2 align-items-center">
            <div class="dropdown">

                <select id="sort-select" class="sort-select w-100">
                    <option value="featured">Sort by: Featured</option>
                    <option value="price-asc">Price: Low to High</option>
                    <option value="price-desc">Price: High to Low</option>
                </select>
            </div>
        </div>
        <div class="container">
            <h5 class="fw-bold">Price Range</h5>
            <div class="price-range p-3 border rounded shadow-sm bg-light">
                <div class="price-inputs" id="minmaxfilter">
                    <input type="range" id="price-slider" min="0" max="10000" value="10000"
                        class="form-range filter-range mb-2">

                    <div class="d-flex gap-2">
                        <input type="number" id="min-price" placeholder="Min" min="0" value="0"
                            class="form-control filter-price">
                        <input type="number" id="max-price" placeholder="Max" max="10000" value="10000"
                            class="form-control filter-price">
                    </div>

                    <button id="minmaxfiltersubmit" class="btn btn-primary mt-2">Apply</button>
                </div>
            </div>
        </div>
    </div>

    <div class="row g-4">
        <?php $this->getChildHtml('filter') ?>
        <?php $this->getChildHtml('products') ?>
    </div>
</div>