<?php
$id = Mage::getSingleton('core/request')->getQuery('id');
$categories = $this->getcategories();
$products = $this->getProducts();
$attributes = $this->getAttribute();
?>
<div class="container py-5">
    <div
        class="d-flex flex-column flex-md-row justify-content-between align-items-center bg-light rounded-3 p-4 shadow-sm mb-4">
        <h4 class="mb-2 mb-md-0 fw-bold text-primary">
            <?php echo ($id) ? $this->getCategoryName($id) : "All" ?> Category Products
        </h4>
        <div class="d-flex flex-column align-items-center">
            <!-- <h2 class="fs-5 text-secondary mb-2">Search Product Name</h2> -->
            <input type="text" id="search-input" class="form-control w-100 w-md-75" placeholder="Search product name"
                oninput="filterProducts()">
        </div>
        <div class="d-flex gap-2 align-items-center">
            <div class="dropdown">

                <select id="sort-select" class="sort-select w-100" onchange="sortProducts()">
                    <option value="featured">Sort by: Featured</option>
                    <option value="price-asc">Price: Low to High</option>
                    <option value="price-desc">Price: High to Low</option>
                    <!-- <option value="newest">Newest Arrivals</option>
                    <option value="popularity">Popularity</option> -->
                </select>
            </div>
        </div>
    </div>

    <div class="row g-4">
        <?php $this->getChildHtml('filter') ?>
        <?php $this->getChildHtml('products') ?>
    </div>
</div>