<?php
$queryParams = $_GET;
unset($queryParams['export'], $queryParams['exportall']);
$baseQuery = http_build_query($queryParams);
$baseUrl = !empty($baseQuery) ? "?" . $baseQuery . "&" : "?";
?>
<a href="<?php echo $baseUrl; ?>export=true" class="btn btn-sm btn-outline-secondary">
    <i class="fa-solid fa-file-export"></i> Export
</a>
<a href="<?php echo $baseUrl; ?>exportall=true" class="btn btn-sm btn-outline-secondary">
    <i class="fa-solid fa-file-export"></i> ExportAll
</a>