<br><br>
<div class="d-flex justify-content-center align-items-center vh-100">
    <div class="card p-4 shadow-lg" style="width: 350px;">
        <h4 class="text-center mb-3">Change Password</h4>
        <p class="text-muted text-center">Enter your old Password and Update your password</p>
        <form id="forgetForm">
            <div class="mb-3">
                <label for="oldpassword" class="form-label">old password</label>
                <input type="password" class="form-control" id="oldpassword" name="oldpassword">
            </div>
            <div class="mb-3">
                <label for="newpassword" class="form-label">new password</label>
                <input type="password" class="form-control" id="newpassword" name="newpassword">
            </div>
            <div class="mb-3">
                <label for="confirmpassword" class="form-label">confirm password</label>
                <input type="password" class="form-control" id="confirmpassword" name="confirmpassword">
                <span class="text-danger" id="error-span"></span>
            </div>
            <button type="submit" class="btn btn-primary w-100">Change Password</button>
        </form>
        <div class="card p-4 d-none shadow-lg text-center w-100 w-sm-50 mx-auto" id="success-message">
            <h4 class="text-success"></h4>
            <p class="text-muted">You can now return to your dashboard.</p>
            <a href="<?php echo $this->getUrl('*/*/dashboard'); ?>" class="btn btn-success w-100">Back to Dashboard</a>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        $("#forgetForm").on('submit', function(event) {
            event.preventDefault();
            $.ajax({
                url: "http://localhost/ecommerceweb/customer/account/changepasPost",
                type: "POST",
                data: {
                    oldpassword: $('#oldpassword').val(),
                    newpassword: $('#newpassword').val(),
                    confirmpassword: $('#confirmpassword').val()
                },
                // dataType: "json",    
                success: function(response) {
                    let res = JSON.parse(response);
                    console.log(res.success);

                    if (res.success) {
                        $('#forgetForm').addClass("d-none");
                        $('.text-success').text(res.message);
                        $('#success-message').removeClass("d-none");
                    } else {
                        $('#error-span').text(res.message);
                    }
                },
                error: function() {
                    console.log("error2");
                }
            });

        });
    });
</script>