<div class="d-flex justify-content-center align-items-center vh-100">
    <div class="card p-4 shadow-lg" style="width: 350px;">
        <h4 class="text-center mb-3">Change Password</h4>
        <p class="text-muted text-center">Enter your old Password and Update your password</p>
        <form id="forgetForm">
            <div class="mb-3">
                <label for="oldpassword" class="form-label">old password</label>
                <input type="password" class="form-control" id="oldpassword" name="oldpassword">
                <span id="error-oldpas"></span>
            </div>
            <div class="mb-3">
                <label for="newpassword" class="form-label">new password</label>
                <input type="password" class="form-control" id="newpassword" name="newpassword">
                <span id="error-newpas"></span>
            </div>
            <div class="mb-3">
                <label for="confirmpassword" class="form-label">confirm password</label>
                <input type="password" class="form-control" id="confirmpassword" name="confirmpassword">
                <span id="error-conpas"></span>
            </div>
            <button type="submit" class="btn btn-primary w-100">Change Password</button>
        </form>
        <div class="text-center mt-3">
            <a href="login.html">Back to Login</a>
        </div>
    </div>
</div>
<script>
$(document).ready(function() {
    $("#forgetForm").on('submit', function(event) {
        event.preventDefault();
        $.ajax({
            url: "http://localhost/ecommerceweb/customer/account/changepasPost",
            type: "POST",
            data: {
                oldpassword: $('#oldpassword').val(),
                newpassword: $('#newpassword').val(),
                confirmpassword: $('#confirmpassword').val()
            },
            // dataType: "json",
            success: function(res) {
                // let data = JSON.parse(res);
                // if (data.success) {
                console.log("success");
                console.log(res);
                // } else {
                //     console.log("error");
                // }
            },
            error: function() {
                console.log("error2");
            }
        });

    });
});
</script>