<br><br>
<div class="d-flex justify-content-center align-items-center vh-100">
    <div class="card p-4 shadow-lg">
        <div id="forgotdiv">
            <h4 class="text-center mb-3">Forgot Password</h4>
            <p class="text-muted text-center">Enter your email to reset your password</p>
            <div class="d-flex align-items-center mb-3" id="emaildiv">
                <input type="email" class="form-control me-2" id="email" placeholder="Enter your email">
                <button type="button" class="btn btn-primary" id="verifyEmail">Verify Email</button>
            </div>
            <div id="otpdiv" class="d-flex d-none align-items-center mb-3">
                <input type="text" class="form-control me-2" id="otp" placeholder="Enter OTP">
                <button type="button" id="verifyOtp" class="btn btn-success">Verify OTP</button>
            </div>
            <div class="mb-3">
                <input type="password" class="form-control" id="newPassword" placeholder="New Password">
            </div>
            <div class="mb-3">
                <input type="password" class="form-control" id="confirmPassword" placeholder="Confirm New Password">
            </div>
            <span class="text-danger" id="error-span"></span>
            <button id="resetPassword" class="btn btn-primary w-100">Reset Password</button>
            <div class="text-center mt-3">
                <a href="<?php echo $this->getUrl('*/*/login'); ?>">Back to Login</a>
            </div>
        </div>
        <div class="card p-4 d-none shadow-lg text-center w-100 w-sm-50 mx-auto" id="success-message">
            <h4 class="text-success"></h4>
            <p class="text-muted">You can now return to your login.</p>
            <a href="<?php echo $this->getUrl('*/*/login'); ?>" class="btn btn-success w-100">Back to Login</a>
        </div>
    </div>
</div>
<script>
$(document).ready(function() {
    console.log($("#sapn1").html());
    $("#verifyEmail").on('click', function(event) {
        $.ajax({
            url: "http://localhost/ecommerceweb/customer/account/verifyEmail",
            type: "POST",
            data: {
                email: $('#email').val()
            },
            dataType: "json",
            success: function(response) {
                console.log(response);
                if (response.success) {
                    $('#error-span').text("");
                    alert(response.message);
                    $('#otpdiv').removeClass("d-none");
                } else {
                    $('#error-span').text(response.message);
                }
            },
            error: function() {
                console.log("error2");
            }
        });

    });
    $("#verifyOtp").on('click', function(event) {
        $.ajax({
            url: "http://localhost/ecommerceweb/customer/account/verifyOtp",
            type: "POST",
            data: {
                otpinput: $('#otp').val()
            },
            dataType: "json",
            success: function(response) {
                if (response.success) {
                    $('#error-span').text("");
                    alert(response.message);
                    $('#email').prop('disabled', true);
                    $('#otpdiv').addClass("d-none");
                } else {
                    $('#error-span').text(response.message);
                }
            },
            error: function() {
                console.log("error2");
            }
        });

    });
    $("#resetPassword").on('click', function(event) {
        $.ajax({
            url: "http://localhost/ecommerceweb/customer/account/resetPassword",
            type: "POST",
            data: {
                newpassword: $('#newPassword').val(),
                confirmpassword: $('#confirmPassword').val()
            },
            dataType: "json",
            success: function(response) {
                console.log(response);

                if (response.success) {
                    $('#error-span').text("");
                    $('#forgotdiv').hide();
                    $('#success-message').removeClass('d-none');
                    $('.text-success').text(response.message);
                } else {
                    $('#error-span').text(response.message);
                }
            },
            error: function() {
                console.log("error2");
            }
        });

    });
});
</script>