<form action="<?php echo Mage::getBaseUrl() ?>admin/account/loginPost" method="post"
    class="col-md-5 mx-auto p-5 bg-white shadow-lg rounded-3 border my-5">
    <h2 class="mb-4 text-center fw-bold text-primary">Admin <span class="text-dark">Login</span></h2>

    <div class="form-group mb-4">
        <label for="Username" class="form-label fw-semibold">Username</label>
        <div class="input-group input-group-lg">
            <span class="input-group-text bg-primary text-white"><i class="bi bi-person-fill"></i></span>
            <input type="text" class="form-control form-control-lg shadow-sm m-0" id="Username" name="username"
                placeholder="Enter Username" required>
        </div>
    </div>

    <div class="form-group mb-4 position-relative">
        <label for="floatingPassword" class="form-label fw-semibold">Password</label>
        <div class="input-group input-group-lg">
            <span class="input-group-text bg-primary text-white"><i class="bi bi-lock-fill"></i></span>
            <input type="password" class="form-control form-control-lg shadow-sm m-0 z-0 rounded" id="floatingPassword"
                placeholder="Enter Password" name="password" required>
            <span class="position-absolute top-50 end-0 translate-middle-y me-3" role="button"
                onclick="togglePassword()">
                <i class="fas fa-eye" id="toggleIcon"></i>
            </span>
        </div>
    </div>

    <!-- <div class="form-check mb-4">
        <input class="form-check-input" type="checkbox" value="" id="rememberMe">
        <label class="form-check-label" for="rememberMe">
            Remember me
        </label>
    </div> -->

    <div class="d-grid gap-2 mb-4">
        <button type="submit" class="btn btn-primary btn-lg py-3 fw-bold shadow">LOG IN</button>
    </div>

    <!-- <div class="text-center">
        <a href="#" class="text-decoration-none text-primary fw-semibold">Forgot Password?</a>
    </div> -->
</form>